# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: prodbyEDDY.VCam
PackageVersion: 0.2.4
InstallerType: nullsoft
Scope: machine
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: VCam 0.2.4
  Publisher: prodbyEDDY
  DisplayVersion: 0.2.4
  ProductCode: 3ff96593-c010-574e-83ce-f853f79cc1a0
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/prodbyEDDY/vcam/releases/download/v0.2.4/VCam-Setup-0.2.4-x64.exe
  InstallerSha256: 9D90B78EDCEFA9B607AA99799E86C8648402461EBA4223B637E8C6D67EFD6B64
ManifestType: installer
ManifestVersion: 1.12.0
